services:
  purchases-bot:
    build: .
    container_name: purchases-bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SOURCE_ID: goszakupki.by
      SOURCE_BASE_URL: https://goszakupki.by/tenders/posted
      SOURCE_PAGES_DEFAULT: ${SOURCE_PAGES_DEFAULT:-3}
      CHECK_INTERVAL_DEFAULT: ${CHECK_INTERVAL_DEFAULT:-300}
      HTTP_TIMEOUT_SECONDS: ${HTTP_TIMEOUT_SECONDS:-30}
      HTTP_CONCURRENCY: ${HTTP_CONCURRENCY:-3}
      RATE_LIMIT_RPS: ${RATE_LIMIT_RPS:-2}
      HTTP_VERIFY_SSL: ${HTTP_VERIFY_SSL:-0}
      # Detail scanner config
      DETAIL_INTERVAL_SECONDS: ${DETAIL_INTERVAL_SECONDS:-3}
      DETAIL_MAX_RETRIES: ${DETAIL_MAX_RETRIES:-5}
      DETAIL_BACKOFF_BASE_SECONDS: ${DETAIL_BACKOFF_BASE_SECONDS:-60}
      DETAIL_BACKOFF_FACTOR: ${DETAIL_BACKOFF_FACTOR:-2.0}
      DETAIL_BACKOFF_MAX_SECONDS: ${DETAIL_BACKOFF_MAX_SECONDS:-3600}
      DB_PATH: /data/app.db
      TZ: Europe/Helsinki
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      GZ_LIST_ITEM: ${GZ_LIST_ITEM}
      GZ_TITLE: ${GZ_TITLE}
      GZ_LINK: ${GZ_LINK}
      GZ_ID_TEXT: ${GZ_ID_TEXT}
      GZ_ID_FROM_HREF: ${GZ_ID_FROM_HREF:-0}
      USE_PLAYWRIGHT: ${USE_PLAYWRIGHT:-0}
      # Auth gate (optional). When set, bot requires /login
      AUTH_LOGIN: ${AUTH_LOGIN}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
    volumes:
      - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import os,sqlite3,sys; p=os.getenv('DB_PATH','/data/app.db'); con=sqlite3.connect(p); con.execute('PRAGMA quick_check'); con.close()\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
